### PR TITLE
Add support for verifying the SSL certificate presented by the backing mongo

### PR DESCRIPTION
**Pull request by tolsen**

### CODE REVIEW

**Comment by tolsen** [comment]
cc @erh

**Comment by tolsen** [comment]
good catch. Should I have those binaries continue to skip SSL verification or should I add an option to both of them for specifying a CA file?

**Comment by erh** [comment]
I think just having them continue to skip ssl verification is easiest and fine for now

**Comment by tolsen** [comment]
Ok. done

**Pull request merged**
